### PR TITLE
Fix error handling using non-existent error function

### PR DESCRIPTION
**Pull request by kammerer**
Replace non-existent `error` function with `warning`.

### CODE REVIEW

**Comment by TransGirlCodes** [comment]
Ah, the drawback of trying to learn multiple languages, in julia it's `error`, in R I meant to use the `stop` function.

**Comment by kammerer** [comment]
Oh, I wasn't aware of `stop` as I do not know R too well myself. It makes more sense than what I initially used.

**Comment by aliceminotto** [comment]
@Ward9250 Can this be merged? I'll update the CyVerse app afterwards

**Comment by TransGirlCodes** [comment]
Looks good to me :shipit:

**Pull request merged**
